# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: #http://mazhuang.org
date_format: "ordinal"
title: GitHub
subtitle: "Main Page"
description: "孟伟的个人博客"
keywords: 孟伟,GITHUB
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Wei Meng
organization: ZTE, Inc.
organization_url: https://www.sogou.com
location: Shanghai, China
email: mengwei1101@hotmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: mzlogin/mzlogin.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: tsbxmw

#douban_username: freedim
#facebook_username: mzlogin
weibo_username: 18842601728
zhihu_username: 18842601728
#twitter_username: mzlogin

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
#duoshuo_username: 
#disqus_username: mzlogin
# 在使用 disqus 的时候可点击显示多说评论框
#lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C, Python]
skill_mobile_app_keywords: [Android, AutoTest Engineering]
skill_windows_keywords: [VS2010,BAT,Uiautomator,Espresso,Jenkins]
